export const ADD_ARTICLE = "ADD_WISHITEM";
export const UPDATE_ARTICLE = "UPDATE_WISHITEM";
export const SELECT_ARTICLE = "SELECT_WISHITEM";
export const DELETE_ARTICLE = "DELETE_WISHITEM";

export const OPEN_FORM = "OPEN_FORM";
export const CLOSE_FORM = "CLOSE_FORM";
export const OPEN_EDIT_FORM = "OPEN_EDIT_FORM";
export const CLOSE_EDIT_FORM = "CLOSE_EDIT_FORM";
